import { describe, expect, it } from 'vitest'
import { gzipSync, gunzipSync } from 'node:zlib'
import { execFileSync } from 'node:child_process'
import { configKey, configKeyText, toPlist, encryptRnc, decryptRnc, encodeExamFile, decodeExamFile,
  passwordHash, labSettings, requestHash, matchesConfigProof, MAX_BYTES } from './config.mjs'
import { verifySebRequestHashes } from '../../lib/seb.ts'

const LAB_OPEN_PASSWORD = 'Synthetic-open-password'
const settings = (overrides = {}) => ({ ...labSettings({ startUrl: 'https://exam.example/lab/a',
  quitPassword: 'Synthetic-quit-A', adminPassword: 'Synthetic-admin-A', salt: Buffer.alloc(32, 7) }), ...overrides })

describe('independent RNCryptor v3 known-answer vectors', () => {
  // Public, synthetic vectors from RNCryptor-Spec@7aa27298df4d66476e06efeeeeecc6228df6cfbd
  // vectors/v3/password; intentionally not generated by the code under test.
  const vectors = [
    { password: 'a', enc: '0000000000000000', mac: '0000000000000000', iv: '00000000000000000000000000000000', plain: '',
      encrypted: '03010000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 0000b303 9be31cd7 ece5e754 f5c8da17 00366631 3ae8a89d dcf8e3cb 41fdc130 b2329dbe 07d6f4d3 2c34e050 c8bd7e93 3b12' },
    { password: 'thepassword', enc: '0001020304050607', mac: '0102030405060708', iv: '02030405060708090a0b0c0d0e0f0001', plain: '01',
      encrypted: '03010001 02030405 06070102 03040506 07080203 04050607 08090a0b 0c0d0e0f 0001a1f8 730e0bf4 80eb7b70 f690abf2 1e029514 164ad3c4 74a51b30 c7eaa1ca 545b7de3 de5b010a cbad0a9a 13857df6 96a8' },
  ]
  for (const [index, vector] of vectors.entries()) {
    it(`matches published bytes in both directions, vector ${index + 1}`, () => {
      const pieces = [vector.enc, vector.mac, vector.iv].map(value => Buffer.from(value, 'hex'))
      const encrypted = Buffer.from(vector.encrypted.replaceAll(' ', ''), 'hex')
      expect(encryptRnc(Buffer.from(vector.plain, 'hex'), vector.password, () => pieces.shift())).toEqual(encrypted)
      expect(decryptRnc(encrypted, vector.password).toString('hex')).toBe(vector.plain)
    })
  }
})

describe('bounded SEB settings and canonical key', () => {
  it('hashes the documented SEB-JSON bytes, not insertion order or standard JSON escaping', () => {
    const input = { z: [{ Zed: true, abc: false }], StartURL: 'https://exam.example/a', a: 'ก่อครู"\\x', originatorVersion: 'ignored' }
    expect(configKeyText(input)).toBe('{"a":"ก่อครู"\\x","StartURL":"https://exam.example/a","z":[{"abc":false,"Zed":true}]}')
    expect(configKey(input)).toBe(configKey(Object.fromEntries(Object.entries(input).reverse())))
    // Independently checked with printf '%s' '{"a":true}' | shasum -a 256.
    expect(configKey({ a: true })).toBe('5daa0644c4a1c43ea018f7f1ef2944b90e0165ef1f2d5669ca89e5d4f69ac597')
  })
  it('encodes binary salt and recursively excludes metadata/empty dictionaries', () => {
    expect(configKeyText({ salt: Buffer.from([0, 1, 255]), nested: { a: {}, originatorVersion: 'x' }, arr: [], originatorVersion: 'y' }))
      .toBe('{"arr":[],"salt":"AAH/"}')
  })
  it('keeps changes to quit password and security options in CK', () => {
    const original = settings()
    expect(configKey(settings({ hashedQuitPassword: passwordHash('Synthetic-quit-B') }))).not.toBe(configKey(original))
    expect(configKey(settings({ allowQuit: false }))).not.toBe(configKey(original))
    expect(configKey(settings({ originatorVersion: 'unimportant' }))).toBe(configKey(original))
  })
  it.each([null, undefined, new Date(), NaN, Infinity, 0.1, Number.MAX_SAFE_INTEGER + 1, () => 0])('rejects unsupported type/value %s', value => {
    expect(() => configKey({ key: value })).toThrow()
  })
  it('rejects ambiguous keys, cycles, accessors, nested/sparse arrays and invalid XML strings', () => {
    const cycle = {}; cycle.self = cycle
    let getterCalls = 0
    const get = () => { getterCalls++; return 'must not invoke' }
    const accessor = Object.defineProperty({}, 'secret', { enumerable: true, get })
    const arrayAccessor = Object.defineProperty([1], '0', { enumerable: true, get })
    for (const input of [{ lower: true, LOWER: false }, { 'ไทย': true }, cycle, accessor, { arr: arrayAccessor },
      { [Symbol('hidden')]: true },
      { arr: [[1]] }, { arr: new Array(2) }, { x: '\u0000' }, { x: '\ud800' }]) {
      expect(() => toPlist(input)).toThrow()
      expect(() => configKey(input)).toThrow()
    }
    expect(getterCalls).toBe(0)
  })
  it('bounds bytes and nesting', () => {
    let deep = {}; for (let i = 0; i < 18; i++) deep = { nested: deep }
    expect(() => toPlist(deep)).toThrow()
    expect(() => configKey({ large: 'a'.repeat(MAX_BYTES + 1) })).toThrow()
    expect(() => configKey({ many: Array.from({ length: 10001 }, () => true) })).toThrow()
  })
  it.runIf(process.platform === 'darwin')('Apple plutil independently parses generated XML, including UTF-8 and escaped text', () => {
    const input = { ...settings(), startURL: 'https://exam.example/?a=1&b=2', sample: 'ก่อครู <>&"\r\n', items: [1, true, 'text'] }
    // plutil XML -> XML checks every plist type including NSData. JSON cannot represent NSData.
    const parsed = execFileSync('/usr/bin/plutil', ['-convert', 'xml1', '-o', '-', '-'], { input: toPlist(input), encoding: 'utf8' })
    expect(parsed).toContain('<data>')
    expect(parsed).toContain('ก่อครู')
    expect(parsed).toContain('&amp;')
  })
})

describe('SEB pswd packaging and tamper resistance', () => {
  it('produces encrypted exam files with two gzip layers and random salts/IV', () => {
    const a = encodeExamFile(settings(), LAB_OPEN_PASSWORD), b = encodeExamFile(settings(), LAB_OPEN_PASSWORD)
    expect(a.equals(b)).toBe(false)
    expect(gunzipSync(a).subarray(0, 6)).toEqual(Buffer.from([0x70, 0x73, 0x77, 0x64, 3, 1]))
    expect(decodeExamFile(a, LAB_OPEN_PASSWORD)).toBe(toPlist(settings()))
    expect(gunzipSync(a).includes(Buffer.from('<plist'))).toBe(false)
    const largestPlaintext = Buffer.alloc(MAX_BYTES, 17)
    expect(decryptRnc(encryptRnc(largestPlaintext, LAB_OPEN_PASSWORD), LAB_OPEN_PASSWORD)).toEqual(largestPlaintext)
  })
  it('rejects wrong passwords and authenticated header/ciphertext/tag modifications', () => {
    const packed = encodeExamFile(settings(), LAB_OPEN_PASSWORD)
    expect(() => decodeExamFile(packed, 'Wrong-password')).toThrow()
    const original = gunzipSync(packed)
    for (const index of [6, 15, 25, 42, original.length - 1]) {
      const modified = Buffer.from(original); modified[index] ^= 1
      expect(() => decodeExamFile(gzipSync(modified), LAB_OPEN_PASSWORD)).toThrow()
    }
  })
  it('rejects client-purpose files, unsupported envelopes, unicode encryption passwords and bombs', () => {
    expect(() => encodeExamFile(settings({ sebConfigPurpose: 1 }), LAB_OPEN_PASSWORD)).toThrow()
    expect(() => encodeExamFile(settings(), 'รหัสทดสอบ')).toThrow()
    expect(() => decodeExamFile(gzipSync(Buffer.from('pwcc-unexpected')), LAB_OPEN_PASSWORD)).toThrow()
    expect(() => decodeExamFile(gzipSync(Buffer.alloc(MAX_BYTES + 1)), LAB_OPEN_PASSWORD)).toThrow()
    expect(() => decryptRnc(Buffer.alloc(80), LAB_OPEN_PASSWORD)).toThrow()
  })
})

describe('per-config request checks without weakening production BEK validation', () => {
  const url = 'https://exam.example/check?challenge=unique'
  it('rejects wrong config, modified settings, wrong URL and malformed hashes', () => {
    const a = configKey(settings()), b = configKey(settings({ hashedQuitPassword: passwordHash('Synthetic-B') }))
    expect(matchesConfigProof(url, a, requestHash(url, a))).toBe(true)
    expect(matchesConfigProof(url, a, requestHash(url, b))).toBe(false)
    expect(matchesConfigProof(url, a, requestHash(url + '2', a))).toBe(false)
    expect(matchesConfigProof(url, a, 'invalid')).toBe(false)
    expect(requestHash(url + '#fragment', a)).toBe(requestHash(url, a))
  })
  it('the actual production verifier still requires both CK AND BEK', () => {
    const key = configKey(settings()), knownBek = 'b'.repeat(64)
    const proof = { requestUrl: url, configKey: key, browserExamKeys: [knownBek],
      configKeyHash: requestHash(url, key), browserExamKeyHash: requestHash(url, knownBek) }
    expect(verifySebRequestHashes(proof)).toBe(true)
    expect(verifySebRequestHashes({ ...proof, browserExamKeys: [] })).toBe(false)
    expect(verifySebRequestHashes({ ...proof, browserExamKeyHash: requestHash(url, 'c'.repeat(64)) })).toBe(false)
    expect(verifySebRequestHashes({ ...proof, configKey: configKey(settings({ allowQuit: false })) })).toBe(false)
    // knownBek above is synthetic, not evidence of application attestation on any device.
  })
})
